apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-13T19:36:32Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "472"
  uid: 28ff8b88-7ed4-4086-b4c3-b6fe2535a12b
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.160.141
  clusterIPs:
  - 10.110.160.141
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30564
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
